apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasky-deployment
  labels:
    app: tasky
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tasky
  template:
    metadata:
      labels:
        app: tasky
    spec:
      containers:
        - name: tasky-app
          image: tasky-app:latest # Or push to DockerHub/ECR and use repo URL
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: "mongodb://<mongodb-service>:27017/taskydb"
---
apiVersion: v1
kind: Service
metadata:
  name: tasky-svc
spec:
  type: NodePort
  selector:
    app: tasky
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tasky-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: tasky.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tasky-svc
                port:
                  number: 80
