apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasky
  template:
    metadata:
      labels:
        app: tasky
    spec:
      containers:
      - name: tasky
        image: <ECR_REPOSITORY>:latest
        env:
        - name: MONGO_URL
          value: "mongodb://<mongo-vm-private-ip>:27017/tasky"
        volumeMounts: []
      serviceAccountName: admin-sa
---
apiVersion: v1
kind: Service
metadata:
  name: tasky-svc
spec:
  type: ClusterIP
  selector:
    app: tasky
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tasky-ingress
spec:
  rules:
  - host: tasky.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tasky-svc
            port:
              number: 80
