name: App CI
on:
push:
paths:
- 'app/**'


jobs:
build-and-push:
runs-on: ubuntu-latest
env:
REGISTRY: ${{ secrets.REGISTRY }}
IMAGE_NAME: tasky
steps:
- uses: actions/checkout@v4
- name: Login to registry
run: |
echo ${{ secrets.REGISTRY_PASSWORD }} | docker login ${{ secrets.REGISTRY }} -u ${{ secrets.REGISTRY_USER }} --password-stdin
- name: Build image
run: |
docker build -t $REGISTRY/$IMAGE_NAME:latest ./app
- name: Scan with Trivy
uses: aquasecurity/trivy-action@v0.7.0
with:
image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
- name: Push image
run: docker push $REGISTRY/$IMAGE_NAME:latest


deploy:
needs: build-and-push
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- name: Setup kubectl
uses: azure/setup-kubectl@v3
with:
version: 'v1.27.0'
- name: Configure kubeconfig
run: |
echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
- name: Deploy to Kubernetes
run: |
kubectl apply -f app/k8s/
