name: Build and Deploy App
on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build -t ${{ secrets.ECR_REPO }}:latest ./docker-app
    - name: Push Docker image
      run: echo "Push to ECR here"
    - name: Deploy to K8s
      run: kubectl apply -f k8s/
