name: Terraform Deploy
on: [push]
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v2
    - run: terraform init && terraform apply -auto-approve
