name: Infra CI
on:
workflow_dispatch:
push:
paths:
- 'terraform/**'


jobs:
tfsec:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- name: Setup Terraform
uses: hashicorp/setup-terraform@v2
- name: Install tfsec
run: |
curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
- name: tfsec scan
run: tfsec ./terraform || true
- name: Terraform fmt
run: terraform -chdir=terraform fmt -check
- name: Terraform validate
run: terraform -chdir=terraform init && terraform -chdir=terraform validate
- name: Terraform plan
run: terraform -chdir=terraform plan -out=tfplan


apply:
needs: tfsec
runs-on: ubuntu-latest
if: github.ref == 'refs/heads/main' # only auto-apply from main (adjust as needed)
steps:
- uses: actions/checkout@v4
- name: Setup Terraform
uses: hashicorp/setup-terraform@v2
- name: Terraform init
run: terraform -chdir=terraform init
- name: Terraform apply
run: terraform -chdir=terraform apply -auto-approve
